INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (1, 'Men''s Running Shoes', 99.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (2, 'Women''s Tennis Skirt', 49.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (3, 'Men''s Basketball Jersey', 39.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (4, 'Women''s Yoga Leggings', 79.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (5, 'Men''s Golf Polo Shirt', 59.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (6, 'Women''s Running Shorts', 29.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (7, 'Men''s Soccer Socks', 9.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (8, 'Women''s Tennis Dress', 69.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (9, 'Men''s Compression Tights', 49.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (10, 'Women''s Sports Bra', 34.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (11, 'Men''s Baseball Cap', 24.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (12, 'Women''s Hiking Jacket', 129.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (13, 'Men''s Compression Shorts', 39.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (14, 'Women''s Soccer Cleats', 79.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (15, 'Men''s Tennis Polo Shirt', 49.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (16, 'Women''s Running Jacket', 89.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (17, 'Men''s Gym Shorts', 29.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (18, 'Women''s Yoga Tank Top', 24.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (19, 'Men''s Cycling Jersey', 79.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (20, 'Women''s Volleyball Shoes', 69.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (21, 'Men''s Swim Trunks', 34.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (22, 'Women''s Sports Leggings', 59.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (23, 'Men''s Track Jacket', 89.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (24, 'Women''s Golf Polo Shirt', 49.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (25, 'Men''s Soccer Cleats', 79.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (26, 'Women''s Running Shoes', 99.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (27, 'Men''s Tennis Shorts', 39.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (28, 'Women''s Yoga Pants', 79.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (29, 'Men''s Baseball Jersey', 59.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (30, 'Women''s Tennis Shoes', 89.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (31, 'Men''s Compression Shirt', 34.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (32, 'Women''s Sports Shorts', 24.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (33, 'Men''s Golf Pants', 69.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (34, 'Women''s Running Tank Top', 39.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (35, 'Men''s Soccer Jersey', 79.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (36, 'Women''s Yoga Mat', 29.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (37, 'Men''s Basketball Shorts', 49.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (38, 'Women''s Volleyball Shorts', 39.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (39, 'Men''s Swim Goggles', 19.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (40, 'Women''s Golf Skirt', 59.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (41, 'Men''s Tennis Shoes', 99.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (42, 'Women''s Compression Shorts', 34.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (43, 'Men''s Running Jacket', 89.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (44, 'Women''s Tennis Shorts', 39.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (45, 'Men''s Gym Tank Top', 24.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (46, 'Women''s Yoga Top', 29.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (47, 'Men''s Cycling Shorts', 49.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (48, 'Women''s Baseball Cap', 19.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (49, 'Men''s Hiking Shoes', 89.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (50, 'Women''s Swim Swimsuit', 59.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (51, 'Men''s Basketball Shoes', 99.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (52, 'Women''s Golf Gloves', 19.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (53, 'Men''s Soccer Shorts', 39.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (54, 'Women''s Running Visor', 14.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (55, 'Men''s Tennis Racket', 69.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (56, 'Women''s Compression Socks', 29.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (57, 'Men''s Golf Gloves', 19.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (58, 'Women''s Basketball Shorts', 39.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (59, 'Men''s Running Shorts', 29.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (60, 'Women''s Tennis Racket', 89.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (61, 'Men''s Soccer Ball', 24.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (62, 'Women''s Hiking Shoes', 99.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (63, 'Men''s Baseball Glove', 39.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (64, 'Women''s Yoga Block', 14.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (65, 'Men''s Tennis Balls', 9.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (66, 'Women''s Golf Club Set', 249.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (67, 'Men''s Swim Shorts', 29.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (68, 'Women''s Soccer Ball', 19.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (69, 'Men''s Cycling Helmet', 49.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (70, 'Women''s Baseball Glove', 39.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (71, 'Men''s Hiking Backpack', 79.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (72, 'Women''s Yoga Strap', 9.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (73, 'Men''s Tennis Grip Tape', 4.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (74, 'Women''s Golf Ball Set', 24.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (75, 'Men''s Soccer Goalkeeper Gloves', 49.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (76, 'Women''s Running Headband', 9.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (77, 'Men''s Gym Gloves', 19.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (78, 'Women''s Tennis Grip Tape', 4.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (79, 'Men''s Cycling Water Bottle', 9.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (80, 'Women''s Baseball Bat', 49.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (81, 'Men''s Hiking Hat', 14.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (82, 'Women''s Yoga Mat Bag', 19.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (83, 'Men''s Tennis Headband', 4.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (84, 'Women''s Golf Tee Set', 9.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (85, 'Men''s Soccer Goal', 79.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (86, 'Women''s Running Gloves', 14.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (87, 'Men''s Gym Towel', 9.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (88, 'Women''s Tennis Headband', 4.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (89, 'Men''s Cycling Gloves', 19.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (90, 'Women''s Baseball Batting Gloves', 24.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (91, 'Men''s Hiking Compass', 9.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (92, 'Women''s Yoga Bolster', 29.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (93, 'Men''s Tennis Vibration Dampener', 4.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (94, 'Women''s Golf Towel', 9.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (95, 'Men''s Soccer Shin Guards', 29.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (96, 'Women''s Running Arm Sleeves', 14.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (97, 'Men''s Gym Water Bottle', 4.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (98, 'Women''s Tennis Balls', 9.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (99, 'Men''s Cycling Sunglasses', 49.99);
INSERT INTO Products (Product_Id, Product_Name, Product_Price)VALUES (100, 'Women''s Baseball Bat Bag', 29.99);
